const ADD_MOVIE = 'ADD_MOVIE';
const REMOVE_MOVIE = 'REMOVE_MOVIE';
const UPDATE_MOVIE = 'UPDATE_MOVIE';
const RESET_MOVIE = 'RESET_MOVIE';

export default {
	ADD_MOVIE,
	REMOVE_MOVIE,
	UPDATE_MOVIE,
	RESET_MOVIE
}
