const ADD_ACTOR = 'ADD_ACTOR';
const REMOVE_ACTOR = 'REMOVE_ACTOR';
const UPDATE_ACTOR = 'UPDATE_ACTOR';
const RESET_ACTORS = 'RESET_ACTORS';

export default {
	ADD_ACTOR,
	REMOVE_ACTOR,
	UPDATE_ACTOR,
	RESET_ACTORS
}
